name: Publish Docker image
on:
  workflow_run:
    workflows: ["Test 750words-client"]
    types: [completed]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image and push it to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}
          context: .
          cache-from: type=registry,ref=${{ github.repository }}
          cache-to: type=inline
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}

  notify_failure:
    name: "Produce error message"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Error message
        run: |
          echo "::error::Test of 750words-client failed, not publishing new Docker image."
          exit 1
